#!/bin/bash

IFSORG="$IFS"

SDK=${SDK:-4.5}

option=compile
[[ $# -gt 0 && "x`echo "$1" | sed -n '/\(build\|compile\|run\|exec\|execute\)/p'`" != "x" ]] && option="$1" && shift

bin=""
[ $# -gt 0 ] && bin="$1.exe" && shift
IFS=$'\n'; bins=(`ls -1 *exe 2>/dev/null`); IFS=$IFSORG
[ ${#bins[@]} -gt 0 ] && for f in "${bins[@]}"; do [ "x$bin" == "x" ] && bin="$f" && continue; [ "x$bin" != "x$f" ] && rm ./$f*; done
[ "x$bin" == "x" ] && bin="demo.exe"

project="${bin%.exe}"
[ -d "$project" ] && cd $project

case "$option" in
  "compile")
    flags="-debug -sdk:$SDK -nowarn:219"
    refs=`cat refs 2>/dev/null` && [ "x$refs" != "x" ] && refs="-r:$refs"
    [ "x$SDK" == "x4.5" ] && refs="$refs -lib:/usr/local/lib/mono/gac"
    # sdk 4.5 target results in Npgsql.dll version / gac path resolution issue, so be explicit
    mcs $flags $refs *.cs -out:"$project".exe
    ;;
  "run"|"exec"|"execute")
#    MONO_LOG_LEVEL=debug \
    mono "$project".exe
    ;;
esac
